### ISSUE TITLE
ModuleNotFoundError: No module named 'glasto._custom'

### ISSUE THREAD

**Issue by ghost** [thomasms/glastoselenium#11]
I've tried this out on Windows and OSX, added chromedriver to path using multiple methods but still get the following:

Traceback (most recent call last):
  File "scripts/glasto2020.py", line 60, in <module>
    from glasto._custom.driver import DRIVER_PATH
ModuleNotFoundError: No module named 'glasto._custom'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/glasto2020.py", line 66, in <module>
    "Requires chromedriver - set the path via env variable CHROMEDRIVER")
RuntimeError: Requires chromedriver - set the path via env variable CHROMEDRIVER

**Comment by ghost** [comment]
Resolved, had to move glasto into /scripts/
